# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blogengine.Tag'),
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together=set([('pub_date',)]),
        ),
    ]
