# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 22:25
from __future__ import unicode_literals

import datetime
import blogengine.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_fr', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
                ('slug_en', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
                ('slug_fr', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to=blogengine.models.upload_path)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('keywords_en', models.TextField(blank=True, null=True)),
                ('keywords_fr', models.TextField(blank=True, null=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('title_en', models.CharField(default='', max_length=200, null=True)),
                ('title_fr', models.CharField(default='', max_length=200, null=True)),
                ('text', models.TextField(default='')),
                ('text_en', models.TextField(default='', null=True)),
                ('text_fr', models.TextField(default='', null=True)),
                ('slug', models.SlugField(unique=True)),
                ('slug_en', models.SlugField(null=True, unique=True)),
                ('slug_fr', models.SlugField(null=True, unique=True)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogengine.Category')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_fr', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
                ('slug_en', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
                ('slug_fr', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blogengine.Tag'),
        ),
    ]
